### PR TITLE
First stab at middleware

### PR DESCRIPTION
**Pull request by chanan**
This is a first stab at middleware.

You can see I created a class called Logger - it does get the state and action but doesn't print them out yet Might need to use reflection to print them not sure. Also added to inline logger around the Logger class you can see that in program.cs 

So basically just like middleware in aspnetcore (indeed I lifted the source code from aspnet) you can define middle in two ways:

Either inline in program.cs (PS - I had to do something ugly there because it needs IServiceProvider and not IServiceCollection, so I had to list out the store from the configure lambda, or you can define a class with either an Invoke (or InvokeAsync) method.

Still to do:

1. Clean up the code, cleanup UseMiddlewateExtensions is esp. messy still.
2. Allow usage of IMiddleware
3. Allow extra params in the Middleware class in ctor and Invoke
4. Move Location handling to Middleware?

Please give me your thoughts on what I have so far.

### CODE REVIEW

**Comment by chanan** [comment]
@torhovland I am a bit stuck.

This wont work right: 
```

builder.Use(async (state, action, next) =>
{
  Console.WriteLine("Inline logger old state: {0}", JsonUtil.Serialize(state));
  Console.WriteLine("Inline logger: {0}", JsonUtil.Serialize(action));
  await next();
  Console.WriteLine("Inline logger new state: {0}", JsonUtil.Serialize(state));
});
```

In the last line the "new state" will print out the same state as the first line. The reason why this work is aspnet core middleware and not in here is when you for example you mdoe something like this in aspnet middleware:

```
app.Use( context, next => 
{
  context.Request.Headers.add("myHeader", "myValue");
  next();
});  
```

And then you can see the change in a later middleware is that context in aspnet doesn't change objects, while in blazor-redux it does (in the roor reducer, `return new MyState ( ... );`. I tried to pass it by ref but since lambda's dont work with ref that doesnt work.

I am not sure what to do to fix this. Any thoughts?

**Comment by torhovland** [comment]
Hi, @chanan !

I believe your delegate needs to return the new state:

```csharp
public delegate Task<TState> StoreEventDelegate<TState, TAction>(TState state, TAction action);
```

Then you can access the old and new state like this:

```csharp
        public async Task InvokeAsync(TState state, TAction action)
        {
            Console.WriteLine("State before action: {0}", _serialize(state));
            Console.WriteLine("Action: {0}", _serialize(action));
            var newState = await _next(state, action);
            Console.WriteLine("State after action: {0}", _serialize(newState));
        }
```

Having said that, I don't think we actually want to have async middleware, so it would instead be like this:

```csharp
        public void InvokeAsync(TState state, TAction action)
        {
            Console.WriteLine("State before action: {0}", _serialize(state));
            Console.WriteLine("Action: {0}", _serialize(action));
            var newState = _next(state, action);
            Console.WriteLine("State after action: {0}", _serialize(newState));
        }
```

**Comment by chanan** [comment]
@torhovland I tried that and it wasn't working, I gave up and forgot about it, but yes you are right that was the way to go, I will go back and take a second look.

@galvesribeiro Yep, I plan to use JSInterop for the log messages, just need to get everything working first. Thanks for the gist!

**Comment by chanan** [comment]
@torhovland Next problem :)

The problem is how to allow middlware to dispatch actions , if you look in the new project I added BlazorReduxLocation -> Location.cs, Line 31. You will see that it won't compile (ignore the ugly _store.Dispath syntax, dispatch function should be supplied to the middleware but haven't done that yet) - The issue is that even though NewLocationAction implements IAction, it can't be cast to TAction.

I think maybe if Store changes to Store<TState, IAction> or using where on TAction it would fix the issue.

What do you think?

**Pull request closed without merging**
